RELIQUARY_STATS = {
    "FIGHT_PROP_CRITICAL": "CRIT Rate",
    "FIGHT_PROP_CRITICAL_HURT": "CRIT DMG",
    "FIGHT_PROP_HEAL_ADD": "Healing Bonus",
    "FIGHT_PROP_HEALED_ADD": "Incoming Healing Bonus",
    "FIGHT_PROP_CHARGE_EFFICIENCY": "Energy Recharge",
    "FIGHT_PROP_SHIELD_COST_MINUS_RATIO": "Shield Strength",
    "FIGHT_PROP_FIRE_ADD_HURT": "Pyro DMG Bonus",
    "FIGHT_PROP_WATER_ADD_HURT": "Hydro DMG Bonus",
    "FIGHT_PROP_GRASS_ADD_HURT": "Dendro DMG Bonus",
    "FIGHT_PROP_ELEC_ADD_HURT": "Electro DMG Bonus",
    "FIGHT_PROP_WIND_ADD_HURT": "Anemo DMG Bonus",
    "FIGHT_PROP_ICE_ADD_HURT": "Cryo DMG Bonus",
    "FIGHT_PROP_ROCK_ADD_HURT": "Geo DMG Bonus",
    "FIGHT_PROP_PHYSICAL_ADD_HURT": "Physical DMG Bonus",
}

ICON_REFERENCE = {
    "Max HP": "HP",
    "ATK": "ATTACK",
    "DEF": "DEFENSE",
    "CRIT Rate": "CRITICAL",
    "CRIT DMG": "CRITICAL_HURT",
    "Energy Recharge": "CHARGE_EFFICIENCY",
    "Elemental Mastery": "ELEMENT_MASTERY",
    "Electro DMG Bonus": "ELECTRO",
    "Hydro DMG Bonus": "HYDRO",
    "Anemo DMG Bonus": "ANEMO",
    "Cryo DMG Bonus": "CRYO",
    "Dendro DMG Bonus": "DENDRO",
    "Pyro DMG Bonus": "PYRO",
    "Geo DMG Bonus": "GEO",
    "Incoming Healing Bonus": "HEALED_ADD",
    "Healing Bonus": "HEAL_ADD",
    "Physical DMG Bonus": "PHYSICAL_ADD_HURT",
    "Shield Strength": "SHIELD_COST_MINUS_RATIO",
    "1": "ONE_STAR",
    "2": "TWO_STAR",
    "3": "THREE_STAR",
    "4": "FOUR_STAR",
    "5": "FIVE_STAR",
}

ELEMENT_REFERENCE = {
    "FIGHT_PROP_FIRE_ADD_HURT": "PYRO",
    "FIGHT_PROP_WATER_ADD_HURT": "HYDRO",
    "FIGHT_PROP_GRASS_ADD_HURT": "DENDRO",
    "FIGHT_PROP_ELEC_ADD_HURT": "ELECTRO",
    "FIGHT_PROP_WIND_ADD_HURT": "ANEMO",
    "FIGHT_PROP_ICE_ADD_HURT": "CRYO",
    "FIGHT_PROP_ROCK_ADD_HURT": "GEO",
    "FIGHT_PROP_PHYSICAL_ADD_HURT": "PHYSICAL_ADD_HURT",
}

SUBST_ORDER = [
    "FIGHT_PROP_CRITICAL",
    "FIGHT_PROP_CRITICAL_HURT",
    "FIGHT_PROP_ATTACK_PERCENT",
    "FIGHT_PROP_ATTACK",
    "FIGHT_PROP_DEFENSE_PERCENT",
    "FIGHT_PROP_DEFENSE",
    "FIGHT_PROP_HP_PERCENT",
    "FIGHT_PROP_HP",
    "FIGHT_PROP_ELEMENT_MASTERY",
    "FIGHT_PROP_CHARGE_EFFICIENCY",
]