RELIQUARY_STATS = [
    "FIGHT_PROP_CRITICAL",
    "FIGHT_PROP_CRITICAL_HURT",
    "FIGHT_PROP_HEAL_ADD",
    "FIGHT_PROP_HEALED_ADD",
    "FIGHT_PROP_CHARGE_EFFICIENCY",
    "FIGHT_PROP_SHIELD_COST_MINUS_RATIO",
    "FIGHT_PROP_FIRE_ADD_HURT",
    "FIGHT_PROP_WATER_ADD_HURT",
    "FIGHT_PROP_GRASS_ADD_HURT",
    "FIGHT_PROP_ELEC_ADD_HURT",
    "FIGHT_PROP_WIND_ADD_HURT",
    "FIGHT_PROP_ICE_ADD_HURT",
    "FIGHT_PROP_ROCK_ADD_HURT",
    "FIGHT_PROP_PHYSICAL_ADD_HURT",
]

RARITY_REFERENCE = {
    "1": "ONE_STAR",
    "2": "TWO_STAR",
    "3": "THREE_STAR",
    "4": "FOUR_STAR",
    "5": "FIVE_STAR",
}

ELEMENT_REFERENCE = {
    "FIGHT_PROP_FIRE_ADD_HURT": "PYRO",
    "FIGHT_PROP_WATER_ADD_HURT": "HYDRO",
    "FIGHT_PROP_GRASS_ADD_HURT": "DENDRO",
    "FIGHT_PROP_ELEC_ADD_HURT": "ELECTRO",
    "FIGHT_PROP_WIND_ADD_HURT": "ANEMO",
    "FIGHT_PROP_ICE_ADD_HURT": "CRYO",
    "FIGHT_PROP_ROCK_ADD_HURT": "GEO",
    "FIGHT_PROP_PHYSICAL_ADD_HURT": "PHYSICAL_ADD_HURT",
}

SUBST_ORDER = [
    "FIGHT_PROP_CRITICAL",
    "FIGHT_PROP_CRITICAL_HURT",
    "FIGHT_PROP_ATTACK_PERCENT",
    "FIGHT_PROP_ATTACK",
    "FIGHT_PROP_DEFENSE_PERCENT",
    "FIGHT_PROP_DEFENSE",
    "FIGHT_PROP_HP_PERCENT",
    "FIGHT_PROP_HP",
    "FIGHT_PROP_ELEMENT_MASTERY",
    "FIGHT_PROP_CHARGE_EFFICIENCY",
]
